# This is a basic workflow to help you get started with Actions
name: Google Cloud Functions

on:
  push:
    branches: [ "master" ]
jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'temurin'
          cache: maven
      - name: Build with Maven
        run: mvn -B package --file pom.xml

      - id: 'auth'
        uses: 'google-github-actions/auth@v0'
        with:
          credentials_json: '${{ secrets.GCP_CREDENTIALS }}'



      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v0'

      - name: 'Use gcloud CLI'
        run: 'gcloud functions deploy payroll-gcp --entry-point org.springframework.cloud.function.adapter.gcp.GcfJarLauncher --runtime java11 --trigger-http --source target/deploy --memory 512MB'


  #    - id: 'deploy'
  #      uses: 'google-github-actions/deploy-cloud-functions@v0'
  #      with:
  #        name: 'payroll-app'
  #        runtime: 'java11'
  #        entry_point: org.springframework.cloud.function.adapter.gcp.GcfJarLauncher
  #        memory_mb : 512